package de.aoc.y2025;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Day07Test extends AoCTest {
    String input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

    @Test
    public void testPartOne() {
        assertEquals(21, Day07.partOne(input));
        assertEquals(1690, Day07.partOne(readInput()));
    }

    @Test
    public void testPartTwo() {
        assertEquals(40, Day07.partTwo(input));
        assertEquals(221371496188107L, Day07.partTwo(readInput()));
    }
}
